[workspace]
channels = ["conda-forge"]
name = "ped_vs_adults-cxr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.19.*"
aiohappyeyeballs = "==2.4.3"
aiohttp = "==3.10.10"
aiosignal = "==1.3.1"
async-timeout = "==4.0.3"
attrs = "==24.2.0"
certifi = "==2024.8.30"
charset-normalizer = "==3.4.0"
comet-ml = "3.*"
configobj = "==5.0.9"
dulwich = "==0.22.3"
everett = "==3.1.0"
filelock = "==3.16.1"
fire = "==0.6.0"
frozenlist = "==1.4.1"
fsspec = "==2024.10.0"
idna = "==3.10"
jinja2 = "==3.1.4"
jsonschema = "==4.23.0"
jsonschema-specifications = "==2024.10.1"
markdown-it-py = "==3.0.0"
markupsafe = "==3.0.2"
mdurl = "==0.1.2"
mpmath = "==1.3.0"
multidict = "==6.1.0"
networkx = "==3.2.1"
packaging = "==24.1"
pillow = "==11.0.0"
propcache = "==0.2.0"
psutil = "==6.1.0"
pygments = "==2.18.0"
python-box = "==6.1.0"
pyyaml = "==6.0.2"
referencing = "==0.35.1"
requests = "==2.32.3"
requests-toolbelt = "==1.0.0"
rich = "==13.9.3"
rpds-py = "==0.20.0"
simplejson = "==3.19.3"
six = "==1.16.0"
sympy = "==1.13.1"
termcolor = "==2.5.0"
tqdm = "==4.66.5"
triton = "==3.1.0"
typing-extensions = "==4.12.2"
urllib3 = "==2.2.3"
wrapt = "==1.16.0"
wurlitzer = "==3.1.1"
yarl = "==1.16.0"
matplotlib = ">=3.9.4,<4"
seaborn = ">=0.13.2,<0.14"
py-opencv = ">=4.12.0,<5"
imageio = ">=2.37.0,<3"
scikit-image = ">=0.24.0,<0.25"
scikit-learn = ">=1.6.1,<2"
openpyxl = ">=3.1.5,<4"

[feature.torch-gpu.system-requirements]
cuda = "12.0"

[feature.torch-gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "*"

[feature.torch-cpu.dependencies]
pytorch-cpu = "*"

[feature.torch.dependencies]
numpy = "==1.26.4"
pytorch = ">=2.5.0"
torchmetrics = "*"
lightning = "==2.3.3"
pytorch-lightning = "==2.4.0"
torchvision = "*"

[feature.dicom.dependencies]
numpy = ">=2.0.0"
pylibjpeg = "*"
pylibjpeg-openjpeg = "*"
pylibjpeg-libjpeg = "*"

[environments]
dicom = { features = ["dicom"], no-default-feature = false }
torch-gpu = { features = ["torch", "torch-gpu"], no-default-feature = false }
torch-cpu = { features = ["torch", "torch-cpu"], no-default-feature = false }
